# Generated by Django 2.2 on 2019-06-04 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'resources',
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(max_length=255)),
                ('website_url', models.URLField()),
                ('website_description', models.TextField()),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codelibapp.ResourceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'websites',
                'db_table': 'website',
            },
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup_title', models.CharField(max_length=255)),
                ('meetup_url', models.URLField()),
                ('meetup_city', models.CharField(max_length=100)),
                ('meetup_state', models.CharField(max_length=2)),
                ('meetup_description', models.TextField()),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codelibapp.ResourceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'meetups',
                'db_table': 'meetup',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_first_name', models.CharField(max_length=100)),
                ('dev_last_name', models.CharField(max_length=100)),
                ('dev_twitter', models.CharField(max_length=51)),
                ('dev_specialty', models.TextField()),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codelibapp.ResourceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'developers',
                'db_table': 'developer',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_publisher', models.CharField(max_length=255)),
                ('book_pages', models.IntegerField(blank=True, null=True, verbose_name=4)),
                ('book_isbn10', models.CharField(blank=True, max_length=10, null=True)),
                ('book_isbn13', models.CharField(blank=True, max_length=14, null=True)),
                ('book_pub_date', models.DateField(blank=True, null=True)),
                ('book_description', models.TextField()),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codelibapp.ResourceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'books',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_author_first', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_author_last', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_url', models.CharField(max_length=255)),
                ('blog_postdate', models.DateField()),
                ('blog_description', models.TextField()),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codelibapp.ResourceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'blogs',
                'db_table': 'blog',
            },
        ),
    ]
