# Generated by Django 2.2 on 2019-06-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelibapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pages'),
        ),
    ]
