# Generated by Django 2.2 on 2019-06-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelibapp', '0002_auto_20190604_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='dev_topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
